### ISSUE TITLE
Photo Manager does not show fotos on SD card in application specific folder

### ISSUE THREAD

**Issue by mw12345678** [k3b/APhotoManager#131]
I have some photos in subdirectories of
/storage/014A-7323/Android/data/com.nutomic.syncthingandroid/files.
(This is because I synchronize my photos with Syncthing, and that application specific directory is the only directory on the SD card that Syncthing can write to.)

In the folder picker I can go into one of those directories, and A Photo Manager shows a thumbnail of one of the photos in this directory (I regard this as a proof that it has read access to this folder). However, when I select this directory, it will not show the photos of this directory in the gallery view. Instead, it shows photos that are located in other directories.
If I put the photos into a directory at the root of the SD card (e. g. /storage/014A-7323/photos), A Photo Manager works as expected (i. e., it will show exactly the photos of this folder if I select it in the folder picker). The problem seems to only exist for the application specific folders like /storage/014A-7323/Android/data/...
But I have to use the application specific folder because this is the only one that I can synchronize with Syncthing.

I observed the problem on two different smartphones (Samsung Galaxy J3 2016 and Samsung Galaxy J3 2017) as well as on a tablet (Samsung tab E) with different Android versions.

**Comment by k3b** [comment]
Which app version are you using (See menu more/about A Photo manager) ? 0.7.2.181027 is the latest.

Does your special directory (or a parent directory) has a ".nomedia" file?
 
* In [Setting under Diagnostics](https://github.com/k3b/APhotoManager/wiki/settings#Diagnostics) can you enable these setting
  * LogCat SQL: If enabled: Write Database activity to logcat.
  * LogCat jpg: If enabled: trace photo file operations (copy/move/delete). (since 0.6.4)
  * LogCat jpg/xmp metadata: If enabled: Writes infos about reading/writing metadata of jpg/xmp to logcat. (since 0.6.1)
  * LogCat libs: If enabled: Writes infos about of 3rd paty libs to logcat.
  * LogCat Misc.: If enabled: Writes infos about other components to logcat.
* and then click on Clear LogCat
* leave settings
* reproduce the problem you described (open an image with wrong content as decribed)
* go again to settings
* click on Save LogCat to file

after this procedure you should have a detailed logfile what happend.

Can you zip the log file you just created and attach it to this ticket?

**Comment by mw12345678** [comment]
I originally observed the problem with version 0.7.1.180830.

I had a .nomedia file in /storage/.../Android/data (i. e. in a parent directory of my photo directory). I tried to remove it, but this did not help with version 0.7.1.

However, with the latest version 0.7.2.181027 it works now.
I removed the .nomedia file and ran the media scanner on the parent directory of my photos. Then I can select one of the directories and A Photo Manager will display the photos in the gallery view.
I could swear that I tried exactly this procedure with 0.7.2.181027 before I created this ticket, but it seems that I might have done something differently.

The only thing that is a little bit annoying is that before running the media scanner, A Photo Manger still shows photos from different directories (not the selected one). It would be more appropriate to print an error message (maybe telling that the media scanner has to be run before photos from this directory can be shown). But this is not the topic of this ticket.

So this ticket seems to be obsolete. I close it.
Sorry for the noise.
