### ISSUE TITLE
Update wiki now that #115 is closed

### ISSUE THREAD

**Issue by nicolas-raoul** [k3b/APhotoManager#137]
The [Bookmarks wiki](https://github.com/k3b/APhotoManager/wiki/Bookmarks) says:

> Once #115 ("Virtual Albums in Directory Tree) is implemented this will probably change.

Now #115 has been closed, so I guess it is time to remove that sentence, and update the article if needed.

Thanks! :-)

**Comment by k3b** [comment]
ups i forgot to update :-(. Sorry. 

done. :-)

thanks a lot for fixing the other wiki files especially the typos as i am not a native english speaker.

note: i rolled back your changes about "make download less scary" because this is gpl-software and if somebody adds code to my app without publishing the source-code changes (or at least letting me know why the file has grown) i donot want to be held responsible for potential damages. (especially the iranian version that increased from 1.5 Megabytes to 30!)

**Comment by nicolas-raoul** [comment]
Oh, now I understand what you meant. The other versions (such as the cafebazaar  version) probably have all kinds of spyware.

The current sentence is difficult to understand: It sounds like you are saying "The download is very big so be cautious because it can cost you a lot of money if you are not on WiFi".

I suggest rephrasing to: "Please only download from these two trusted sources"

**Comment by k3b** [comment]
ok now i (as non native speaker) understand more.

what i really want to say is. there are versions on the internet that may contain maleware/spyware/adware. be cautions if you download a version that is more than 1.5 megabytes. 

i donot want tell others where to get their software from and i donot know how to say this in a short sentence

**Comment by nicolas-raoul** [comment]
How about this:

"We recommend downloading our app from F-Droid. The APK should not be over 1.5 megabytes."

The "recommend" is softer than my previous sentence :-)
