### ISSUE TITLE
Folders are chaotic by default

### ISSUE THREAD

**Issue by ildar** [k3b/APhotoManager#156]
Settings have several paths and those are spread all over the filesystem. I suggest fixing defaults for that to be sub-`/sdcard/Android/data/$APPID`

**Comment by k3b** [comment]
* thumbnails may be shared by different apps. On very old android devices with low internal memory (i.e. my android-4.2 tablet) they can be put onto sd-card. 
* (mapsforge-) open-streetmap offline maps are shared by different apps (i.e. c:geo) and should there fore be outside the app folder

The database specific and logging specific files could default to /sdcard/Android/data/$APPID/

Since i currently have 3 different $APPID-s ( APhotoManager (last fdroid release), APhotoManager.dev (work in progress( and APhotoManager.a10 (for #155 ) i prefer them using the same database and logging for these.

**Comment by ildar** [comment]
I agree that ../Andoid/data/$APPID/ isn't the best place for those kinds of
data. But the main issue: the app creates too many folders in SDCARD root.

IMHO best choice is subfolder-ing standard Android folders like:
/sdcard/Documents or /sdcard/Download or /sdcard/DCIM (for cache).
