### ISSUE TITLE
An Incompatible API Usage in APP for  "getDrawable(int)"

### ISSUE THREAD

**Issue by PSDroid2022** [k3b/APhotoManager#199]
For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

1. <android.content.Context: android.graphics.drawable.Drawable getDrawable(int)>: [21,30]
``` java
Error path: <de.k3b.android.androFotoFinder.AndroFotoFinderApp: void <init>()>[[]]--><android.content.Context: void <init>()>[]--><android.content.Context: android.graphics.drawable.Drawable getDrawable(int)>
```
You can add an if-then check like "If(Build.VERSION.SDK_INT >= 21)" when invoking this API to prevent compatibility issues.

**Comment by k3b** [comment]
@Valentin-ys 

thanks for the info.

in branch new-DocumentFile and also in branch master and branch fdroid i currently have 

<pre>
public class ResourceUtils {
    public static Drawable getDrawable(Context context, int resID) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return context.getDrawable(resID);
        }
        return context.getResources().getDrawable(resID);
    }

</pre>

i donot understand what is wrong with my code because it already contains  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)

[Update 2022-03-02]

From other github bugreports you made "An Incompatible API Usage..." i see that you are testing your own static code analysis tool.

It would be gread if the tool output contains info about full source file url (or at least which file is affected in which github branch)

[Update]
after further investigation i assume that you analysed the official f-droid-build https://github.com/Valentin-ys/APKs/blob/main/18.APhotoManager-v0.8.3.200315.apk

Seems to be the same false positive as https://github.com/wordpress-mobile/WordPress-Android/issues/16019
