### ISSUE TITLE
Compatibility with new Google Android versions

### ISSUE THREAD

**Issue by Korb** [k3b/APhotoManager#206]
**Describe the bug**
Currently [the app page in F-Droid](https://f-droid.org/en/packages/de.k3b.android.androFotoFinder/) displays a warning when viewed on Google Android 14

> This app was built for an older version of Android and cannot be updated automatically.

**To Reproduce**
1. Open A Photo Manager' page at F-Droid App

**Expected behavior**
There is no incompatibility message, and the application is fully compatible with new versions of Google Android.

**Smartphone (please complete the following information):**

> OS version: Funtouch OS 14
> Model: Vivo T1 (4G) / V2153
> Hardware version: MP_0.1
> Build number: PD22010F_EX_A_14.2.7.2.W20
> Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.71
> Kernel version: 4.19.157-perf+ 1 Fri Mar 1 16:22:31 CST 2024
> Compile time: 1 Mar 2024 11:02:07
> Android security update: 1 March 2024
> Google Play system update: 1 April 2024

A Photo Manager 0.8.3.200315 (47), Mar 14, 2020

**Comment by k3b** [comment]
Since Google Android-10 (=api29) the app does not work any more so the warning will NOT be removed. 

On all my new android devices (android-10 and android-14) the app crashes when executing sql against the media database.

If the app works on your device be happy.

I am happy to have an old Android 7.0 Nougat (API 24) tablet where i can manage my photos...
