### ISSUE TITLE
Use higher thumbnail quality in gallery

### ISSUE THREAD

**Issue by iainnicol** [k3b/APhotoManager#26]
The thumbnails in the gallery view don't look great, especially if you photograph a paper document. Perhaps it's the interpolation algorithm.  Something higher quality should be used.

In contrast, once you're viewing an individual image you can of course zoom out using finger gestures.  If you zoom out to roughly the thumbnail size, it looks much better than the thumbnail back in the gallery view.

Could you please give me a hint where in the codebase I should be looking?

**Comment by k3b** [comment]
the low quality was a compromise to resolve https://github.com/k3b/AndroFotoFinder/issues/10 and https://github.com/k3b/AndroFotoFinder/issues/15.

It saved a lot of memory and loading next/previous image changed from 2 secs to 0.2 secs

as a compromise i can create a setting where you can choose fast+low-quality or highg-quality+slow. would that be ok for you?

**Comment by iainnicol** [comment]
Ah, makes sense.

Sounds good.

Although I wonder if we could do better: initially load low quality, then async on idle load higher quality.  That could avoid #10 although I'm not sure how to avoid #15. I don't have time to try a proof of concept this week, but with any luck over the holidays I might.

**Comment by k3b** [comment]
android 5.1 and below does not support Thumbnails.getThumbnail(...,MediaStore.Images.Thumbnails.FULL_SCREEN_KIND,...) :-(
so i will not fix this

**Comment by keunes** [comment]
@k3b does your last comment (Android 5.1 not supporting x) mean that the following isn't possible?

> i can create a setting where you can choose fast+low-quality or highg-quality+slow

**Comment by k3b** [comment]
@keunes: Technically it is possible to load the full image (2 Secs) instead of the MediaStore.Images.Thumbnails.MINI_KIND preview (0,2 secs) but performance in my opinion would not be acceptable.

The better preview quality (MediaStore.Images.Thumbnails.FULL_SCREEN_KIND) is defined in android but not implemented (at least not in android-5.1).

Any body out there who whants to implement this?

**Comment by k3b** [comment]
[Update] i deleted some conversation in this ticket, because i answered the question "improve initial quality in image-view" while this ticket was about "improve image quality in gallery view". Sorry for this misunderstanding.

Me (or somebody else) can add a setting for better quality pictures in gallery (slower, more memory consumption)

**Comment by k3b** [comment]
Tomorrows 0.5.1 release chaged thumbnail implementation. Hoping this will show enough quality.
