### ISSUE TITLE
Performance improvement suggestion

### ISSUE THREAD

**Issue by struggggle** [k3b/APhotoManager#74]
Dear developers,
I am writing a static code analysis tool to conduct performance analysis for Android apps. I found two violations of bitmap displaying in APhotoManager's code. They could affect performance. 

In the position of APhotoManager's code:
_de.k3b.android.androFotoFinder.imagedetail.HugeImageLoader.loadImage() (line number: 108)_
bitmap object is created with the invocation of decodeFile(). However, decodeFile() is a slow operation and it is in the UI thread. 
Android documentation says this: 
https://developer.android.com/training/displaying-bitmaps/process-bitmap.html
"The BitmapFactory.decode* methods should not be executed on the main UI thread if the source data is read from disk or a network location (or really any source other than memory)."
You can process bitmaps in a background thread using AsyncTask.

In the position of APhotoManager's code:
_de.k3b.android.androFotoFinder.gallery.cursor.GalleryCursorAdapterFromArray.getView() (line number: 110)_
loadImage() will be called many times and new bitmap objects will be created continuously. We know that bitmap objects can consume a large amount of memory. This wastes a lot of CPU cycles in decoding and RAM in storing bitmap objects. On low end devices, GC will kick in frequently because of RAM pressure.

Maybe we can use a memory cache and a disk cache to store the bitmap objects. Then app can reuse them instead of creating new bitmap objects continuously.

Looking forward to your response and hope this information is useful for you.
Thanks.

References: 
https://developer.android.com/training/displaying-bitmaps/cache-bitmap.html
https://www.youtube.com/watch?v=R5ON3iwx78M&index=44&list=PLWz5rJ2EKKc9CBxr3BVjPTPoDPLdPIFCE
https://www.youtube.com/watch?v=JkwrNmCwFfA&index=19&list=PLWz5rJ2EKKc9CBxr3BVjPTPoDPLdPIFCE
http://developer.android.com/training/articles/perf-anr.html

**Comment by k3b** [comment]
Hello struggggle. thankyou for the feedback.

HugeImageLoader.loadImage() is used 

* when you want to have the fullsize view "ImageDetailView" so only 1-3 small images are loaded (current previous, next). since the image is small it is fast enough.
* when you have bigger images (> 1200 pix) `if (size > Global.imageDetailThumbnailIfBiggerThan) ... ` i use a fast thumbnail method wich is also quite fast but requires aditional thumbnail-disk storage.
* GalleryCursorAdapterFromArray is indeed slow but only used in rare cases when you browse photos that sould not be in the media-database (aka ".nomedia folder") and where there should be no cached precalculated thumbnails for privacy reasons. Bbigger Photos in the media-db use a thumb-cache, smaller pictures are fast enough.

before tuning performance. When using the app: do you have the feeling that parts are to slow?

On my android-4.2 tab with about 17000 photos (95% of them are small 1024*x or x*1024) i am not aware of any issues.

My current optimisations where made because i "measured" performance bottle necks.

**Comment by struggggle** [comment]
Hello k3b,
In practical use, I use APhotoManager to browse the photos in the album and it work well (without obvious slow). Thanks for your good work.
The improvement suggestions are come from the detection results of my static code analysis tool, which is designed to detect whether an app exists some space for performance improvement. So I wish the improvement suggestions can help you improve APhotoManager's performance?

**Comment by struggggle** [comment]
Hello k3b,

In practical use, I use APhotoManager to browse the photos in the album and it work well (without obvious slow). Thanks for your good work.

The improvement suggestions are come from the detection results of my static code analysis tool, which is designed to detect whether an app exists some space for performance improvement. So I wish the improvement suggestions can have some help for you to make APhotoManager better.

**Comment by k3b** [comment]
since the code is fast enough, i will not change it for now.
